package pe.edu.unsch.entities;
// Generated 05/07/2019 11:43:54 AM by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private Integer dnidocente;
	private String nombreDocente;
	private Date cargaAcademica;
	private int idSemestreAcademico;

	public Docente() {
	}

	public Docente(String nombreDocente, Date cargaAcademica, int idSemestreAcademico) {
		this.nombreDocente = nombreDocente;
		this.cargaAcademica = cargaAcademica;
		this.idSemestreAcademico = idSemestreAcademico;
	}

	public Integer getDnidocente() {
		return this.dnidocente;
	}

	public void setDnidocente(Integer dnidocente) {
		this.dnidocente = dnidocente;
	}

	public String getNombreDocente() {
		return this.nombreDocente;
	}

	public void setNombreDocente(String nombreDocente) {
		this.nombreDocente = nombreDocente;
	}

	public Date getCargaAcademica() {
		return this.cargaAcademica;
	}

	public void setCargaAcademica(Date cargaAcademica) {
		this.cargaAcademica = cargaAcademica;
	}

	public int getIdSemestreAcademico() {
		return this.idSemestreAcademico;
	}

	public void setIdSemestreAcademico(int idSemestreAcademico) {
		this.idSemestreAcademico = idSemestreAcademico;
	}

}
