package pe.edu.unsch.entities;
// Generated 05/07/2019 11:43:54 AM by Hibernate Tools 5.4.2.Final

/**
 * SemestreAcademico generated by hbm2java
 */
public class SemestreAcademico implements java.io.Serializable {

	private int idSemestreAcademico;
	private String semestre;

	public SemestreAcademico() {
	}

	public SemestreAcademico(int idSemestreAcademico, String semestre) {
		this.idSemestreAcademico = idSemestreAcademico;
		this.semestre = semestre;
	}

	public int getIdSemestreAcademico() {
		return this.idSemestreAcademico;
	}

	public void setIdSemestreAcademico(int idSemestreAcademico) {
		this.idSemestreAcademico = idSemestreAcademico;
	}

	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

}
